image: rocker/tidyverse:latest

stages:
#  - build
#  - document
#  - test
#  - deploy
  - mapapp-base

include:
  - remote: 'https://raw.githubusercontent.com/pnnl-miscscripts/gitlab-lib/v1/gitlab-lib.yaml'

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"

before_script:
  - apt-get update
  - r -e 'devtools::install_deps()'

build:
  tags:
    - k8s
    - rzr
    - codebuilds
  stage: build
  script:
    - r -e 'devtools::build()'

documentation:
  tags:
    - k8s
    - rzr
    - codebuilds
  stage: document
  script:
    - r -e 'devtools::document()'

check:
  tags:
    - k8s
    - rzr
    - codebuilds
  stage: test
  script:
    - r -e 'devtools::check(error_on="error")'

install:
  tags:
    - k8s
    - rzr
    - codebuilds
  stage: deploy
  script:
    - r -e 'devtools::install()'

build_mapapp_base: 
  extends: .pnnllib-gitlab-build-container-image
  stage: mapapp-base
  image:
    name: gcr.io/kaniko-project/executor:v1.5.2-debug
    entrypoint: [""]
  tags:
  - k8s
  - rzr
  - codebuilds
  variables:
    CONTAINER_PREFIX: mapapp-base-
    # CONTAINER_TAG - The container tag to use. Defaults to $CI_COMMIT_TAG
    # CONTAINER_TAG: 0.0.1
    DOCKERFILE: Dockerfile-mapapp-base
    KANIKO_EXTRA_ARGS: "--use-new-run"
