## Creates base image with dependencies for MAP-app

# Install latest version of rocker image
FROM rocker/shiny:4.0.3

# Load general use libraries
RUN apt-get update && apt-get install -y \
    apt-utils \
    sudo \
    pandoc \
    pandoc-citeproc \
    libssl-dev \
    libcurl4-openssl-dev \
    libcairo2-dev \
    libxt-dev \
    libssh2-1-dev \
    libhiredis-dev \
    libzmq3-dev \
    libxml2-dev \
    vim python3-venv

# Install necessary packages
# COPY Install_MAP_Packages.R /srv/shiny/
# WORKDIR /srv/shiny/
# RUN Rscript "Install_MAP_Packages.R"

# Install MAP-app dependencies
RUN Rscript -e 'install.packages(c("shiny", "shinydashboard", "shinydashboardPlus", "shinyWidgets", "DiagrammeR", "DT", "dplyr", "data.table", "purrr", "tidyr", "devtools", "reticulate", "yaml", "waiter", "lifecycle", "fresh", "htmltools", "uuid"), repos="https://cran.rstudio.com")'

# Install shinydashboardPlus version that does not error out. 
RUN Rscript -e "devtools::install_github('RinteRface/shinydashboardPlus@v0.7.5', dependencies = TRUE, repos = 'https://cran.rstudio.com')"

# Set up python virtual env and install mapDataAccess Python dependencies
RUN python3 -m venv venv
RUN venv/bin/pip install --upgrade pip --trusted-host=pypi.org --trusted-host=files.pythonhosted.org 
RUN venv/bin/pip install minio --trusted-host=pypi.org --trusted-host=files.pythonhosted.org  

# Install mapDataAccess R package 
COPY mapdataaccess-lib /tmp/mapDataAccess
RUN Rscript -e "devtools::install_local('/tmp/mapDataAccess', repos='https://cran.rstudio.com')"
